apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: build

resources:
- deployment.yaml
- rolebinding-owner.yaml
- rolebinding.yaml 
- first-configmap.yaml
- second-configmap.yaml
- service-account.yaml


patches:
  - target:
      annotationSelector: "saasiRemoveResource=true"

    patch: |-
     apiVersion: someVersion
     kind: whateverKind
     metadata:
       name: whateverName 
     $patch: delete
