apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Allows deploymentconfigs in this namespace to rollout
      pods in this namespace.  It is auto-managed by a controller; remove subjects
      to disable.
    saasiRemoveResource: true
  creationTimestamp: "2022-11-19T15:13:18Z"
  name: system:deployers
  namespace: gitlab-system
  resourceVersion: "164854425"
  uid: ff2dea7c-ddc1-4419-89c2-92c3df8dff71
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: gitlab-system
